### ISSUE TITLE
Settings module v0.1

### ISSUE THREAD

**Issue by wynlim** [stellar/interstellar-client#1]
Hi @bartekn:
I believe the below is the minimal set of settings we need to have for now:

![settings](https://cloud.githubusercontent.com/assets/51415/8322487/70243f18-1a36-11e5-88f3-112bb345edbe.png)

The interactions should follow the current client. Let me know if you have any questions.

**Comment by bartekn** [comment]
All done, except styling and "Delete Account" - not sure if merging accounts is already implemented in horizon.

**Comment by bekkibolthouse** [comment]
horizon passes any transaction is sees through to stellar-core.  Stellar-core does support account merge (which is how we delete accounts), so this should be possible now.
